os: linux
language: go

jobs:
  include:
    - stage: lint
      os: linux
      dist: focal
      arch: amd64
      group: edge
      go: 1.15.x
      env:
        - lint
      #git:
        #submodules: false # avoid cloning ethereum/tests
      script:
        - go run hello_world.go lint
    - stage: lint
      os: linux
      dist: bionic
      arch: amd64
      group: edge
      go: 1.15.x
      env:
        - lint
      #git:
        #submodules: false # avoid cloning ethereum/tests
      script:
        - go run hello_world.go lint
    - stage: lint
      os: linux
      dist: xenial
      arch: amd64
      group: edge
      go: 1.15.x
      env:
        - lint
      #git:
        #submodules: false # avoid cloning ethereum/tests
      script:
        - go run hello_world.go lint
